# Generated by Django 2.2.6 on 2019-10-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file1',
            field=models.FileField(upload_to='docs'),
        ),
    ]
