# Generated by Django 2.2.6 on 2019-10-16 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20191016_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='docs'),
        ),
    ]
